### PR TITLE
readme.md: typo

### PR DESCRIPTION
**Pull request by grogy**

### CODE REVIEW

**Comment by grogy** [comment]
Is something bad with this (small) PR? I mean that this construct lead developers for better code (great for refactoring, for reading and code consistant). And minimal version PHP for this library is is 5.6 - so this language construct is available.

**Comment by dg** [comment]
Can you chante commit message to something like `readme.md: typo`?

**Comment by grogy** [comment]
Of course, done.

**Comment by dg** [comment]
Thanks

**Pull request merged**
