### PR TITLE
Allow fix of nette/php-generator

### PR DESCRIPTION
**Pull request by maxhelias**
Just allow minor constraint 😄

### CODE REVIEW

**Comment by maxhelias** [comment]
The failure of travis is not related

**Comment by dg** [comment]
Why?

**Comment by maxhelias** [comment]
Version 3.3.1 is available and compatible, it would be cool to have it

**Comment by dg** [comment]
See this https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by maxhelias** [comment]
And the failure was due to the 3.2.0 which has the class `PhpLiteral` in final and which does not have it anymore in 3.2.2

**Comment by maxhelias** [comment]
Oh! Yes, sorry for the inconvenience

**Comment by dg** [comment]
:-)

**Pull request closed without merging**
