### PR TITLE
removed support for section `services` inside extensions [WIP]

### PR DESCRIPTION
**Pull request by dg**
First of all, I'm trying to find out if this feature anyone uses and if is useful.

### CODE REVIEW

**Comment by vysinsky** [comment]
I didn't even know about this feature :) :+1:

**Comment by lookyman** [comment]
Never used it and I don't really see a point in it. Just seems out of place. :+1:

**Comment by matej21** [comment]
:+1:

**Comment by hrach** [comment]
I had no idea it's possible :D

**Comment by enumag** [comment]
I was aware of it but never used it. :+1: for removal.

**Pull request merged**
