### PR TITLE
Update Nette\DI\Container constructor

### PR DESCRIPTION
**Pull request by kolibabchuk**
Result of "?:" operator usage looks more obvious rather than sum of arrays.

- readability
- BC break: no

### CODE REVIEW

**Comment by dg** [comment]
`?:` is short ternary operator, `+` mean merging. To merge both arrays is intention.

**Comment by kolibabchuk** [comment]
Sry, but could you explain? "+" doesn't merge anything. Result is first one not empty array.

Check this: http://sandbox.onlinephpfunctions.com/code/53ea992a86f8b8dafb49aafaa2eeca7ed2c3ee80

**Comment by dg** [comment]
Add custom keys to arrays

**Comment by kolibabchuk** [comment]
@dg now it makes sense, thnx

**Pull request closed without merging**
