### PR TITLE
PhpExtension: fix incorrectly instantiated DateTimes

### PR DESCRIPTION
**Pull request by repli2dev**
Fixies issue #116

### CODE REVIEW

**Comment by dg** [comment]
Isn't it too late to modify parameters in `afterCompile()`? I understand that this is not easy issue, it probably should be solve via some trick.

**Comment by Majkl578** [comment]
Wouldn't this also modify parameters passed explicitly through Configurator::addParameters? That might be unexpected behavior.
And what about DateTimeImmutable?

**Comment by repli2dev** [comment]
@dg I have moved it into `loadConfiguration` which seems also work. Also I have changed behaviour to support `DateTimeImmutable` too (along with DateTime for backward compatibility and cross version use).
Not sure what to do about Configurator::addParameters thought it seems to me as exactly the same problem we are trying to fix just in bootstrap or there is some case in which the fix is unwanted?

**Comment by dg** [comment]
IMHO it will not work when you use parameter inside config, via %date%.

**Comment by repli2dev** [comment]
Could you please elaborate? I am not sure that I understand your note about `%date%` -- is it relevant generally or to the Configurator::addParameters case? (Such as using only %date% in config an then providing this parameter later via the addParameter method?).

**Comment by dg** [comment]
I mean something like 

```
parameters:
    date: 2016-09-01
services:
    - MyClass(%date%)
```

**Comment by repli2dev** [comment]
I have added test showing that when using `loadConfiguration` then the provided use case works (though I have explicitly tested that it is not working with `afterCompile` nor `beforeCompile`).

I have also tested that using `Configurator::addParameters` in current way changes the timezone of all provided DateTimes which we don't know if it's desired. See some thoughts on the topic below.

------

If I am using `Configurator::addParameters` then I am in the bootstrap file before the container is configured, builded... executed. Therefore I am either using the timezone from PHP setting or my own (if I have manually added `date_default_timezone_set` there).

- **Case one**: manually added `date_default_timezone_set`: I know what I am doing, I do not want any of my datetimes to be touched!
- **Case two**: without anything, goes into two subcases
  - **Subcase A**: I have specified timezone of the created Datetime: I know what I am doing, I do not want any of my datetimes to be touched!
  - **Subcase B**: I have not specified timezone: I "expect" them to be in timezone I have configured.

Problem is that the expectation is probably different in config and in bootstrap file. Though I would choose some standardized approach.

Ideas:
 - Translation of all datetimes having the timezone same as the timezone from PHP configuration but that still ommits the case that I want some of my datetimes to be in that zone...
 - Translate only that datetimes coming from config files and ignore the others?

-----

Note: with closer look into allowed date formats accepted by the DateTime construtor I have found that there is even a way how to create dates with time offset (not timezone!) which could help but is not sufficient (as there is only the time offset not the timezone which matters).

**Comment by dg** [comment]
Thanks for test, it really works, because PhpExtension is the first extension.
 
ad questions: what about a different approch? https://github.com/dg/sandbox/commit/7671402b4a85612ac8a911099dff583584feb807

**Pull request closed without merging**
