### PR TITLE
Improved Compiler & Loader extendability

### PR DESCRIPTION
**Pull request by lookyman**

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Can you describe the use case?

**Comment by lookyman** [comment]
```php
<?php

use Tester\Assert;

require __DIR__ . '/../bootstrap.php';

class TestCompiler extends Nette\DI\Compiler
{
	public function createLoader()
	{
		return (new Nette\DI\Config\Loader)->addAdapter('yml', new YmlAdapter);
	}
}

$compiler = new TestCompiler;
$compiler->loadConfig(__DIR__ . '/config.yml');

// Tester::assert(...)
```

And yes, I do realize that currently I have to override a method that is only three lines longer..

**Comment by dg** [comment]
createLoader & createCompiler should be protected.

**Comment by lookyman** [comment]
@dg right..

**Comment by TomasVotruba** [comment]
This looks ready @dg 

Anything else that needs to be done here?

**Comment by Majkl578** [comment]
It needs rebase at least...

**Comment by TomasVotruba** [comment]
Thank you @lookyman

**Comment by lookyman** [comment]
Hmm, coveralls is failing. I can look into writing more tests over the weekend..

**Comment by TomasVotruba** [comment]
I think coveralls is passing, just unhappy about decreasing the coverage.

**Comment by lookyman** [comment]
Ok, added a quick test to make coveralls happy.

**Comment by TomasVotruba** [comment]
Wow, you are awesome. Thanks!

**Comment by f3l1x** [comment]
:+1:

**Comment by TomasVotruba** [comment]
I wonder, correct place to allow extension using constructor injection would be:

```php
public function __construct(ILoader $loader = NULL)
{
	$this->loader = $loader ?: new Loader;
}
```

**Comment by dg** [comment]
To inject different Loader to compiler extension has no sense. Or did you mean a different class?

**Comment by TomasVotruba** [comment]
@dg Do you react to me?
If so,  I mean the same change just via dependency not via child override.

**Comment by dg** [comment]
ad custom loader in Compiler::loadConfig()
- it should be set via code that uses class, no via class itself. Because class can't know what you will pass to loadConfig()
- so IMHO best way is Compiler::loadConfig($file, Loader $loader = NULL) 

ad custom loader in CompilerExtension::loadFromFile()
- CompilerExtension descendant (in contrast with Compiler) knows what is passed to loadFromFile(), so createLoader() is fine

ad custom compiler in ContainerLoader::createCompiler()
- $generator passed to load() allows you to override $compiler, i.e current $compiler is only default value. And it is preferred way, so createCompiler() is not needed.

**Pull request merged**
