### PR TITLE
Container phpstan generics

### PR DESCRIPTION
**Pull request by mabar**
- new feature
- BC break? no
- doc PR: not needed

It helps phpstan understand that returned instance is always instance of $class

### CODE REVIEW

**Comment by dg** [comment]
This would be especially useful for getByType(), wouldn't it?

**Comment by mabar** [comment]
You are right, added

**Comment by dg** [comment]
Hey, isn't this exactly what phpstan does? https://github.com/phpstan/phpstan-nette/blob/master/src/Type/Nette/ServiceLocatorDynamicReturnTypeExtension.php

**Comment by mabar** [comment]
Yes, but native support is imho better than plugin. This way also other static analysis tools and IDEs can understand it. 
Phpstan and psalm are able to share their prefixed docblocks (e.g. psalm uses `@phpstan-param`
IDEs could possibly have native generics support in future, so .phpstorm.meta.php will be not needed (there is already phpstorm plugin https://github.com/Haehnchen/idea-php-generics-plugin)

**Comment by dg** [comment]
I agree that native support is better, but this little bit premature - I'd rather wait until there is an official annotation. Because I think that everybody who analyzes projects in Nette has this plugin.

**Comment by mabar** [comment]
ok

**Comment by hrach** [comment]
Note: these type of annotations also helps devs to easily understand what the method will do.

**Comment by dg** [comment]
@hrach how?

**Comment by hrach** [comment]
It's easier to read this generic type than undestand it from description (because returning an object tells me nothing).

**Comment by dg** [comment]
You're probably an exception, I think the vast majority of PHP programmers don't understand generics yet.

**Pull request closed without merging**
